import * as FileSystem from 'expo-file-system/legacy';

import {
  BuildActivity,
  BuildPhoto,
  BuildTask,
  Part,
  Project,
  VoiceNote,
  normalizePartStatus,
} from '@/types/models';

type ProjectExportInput = {
  project: Project;
  tasks: BuildTask[];
  parts: Part[];
  photos: BuildPhoto[];
  activities: BuildActivity[];
  voiceNotes: VoiceNote[];
};

type ProjectExportResult = {
  fileName: string;
  uri: string;
};

function formatCurrency(value?: number) {
  const safeValue = Number(value || 0);
  const prefix = safeValue < 0 ? '-$' : '$';
  return `${prefix}${Math.abs(safeValue).toLocaleString(undefined, {
    maximumFractionDigits: 2,
  })}`;
}

function formatDate(value?: string) {
  if (!value) return 'Not recorded';

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;

  return date.toLocaleString();
}

function sanitizeFileName(value: string) {
  const cleaned = value
    .trim()
    .replace(/[^a-z0-9-_ ]/gi, '')
    .replace(/\s+/g, '-')
    .toLowerCase();

  return cleaned || 'fabricator-project';
}

function section(title: string, body: string[]) {
  return [`## ${title}`, '', ...body, ''];
}

function bullet(value: string) {
  return `- ${value}`;
}

export function buildProjectExportMarkdown({
  project,
  tasks,
  parts,
  photos,
  activities,
  voiceNotes,
}: ProjectExportInput) {
  const generatedAt = new Date();
  const estimatedParts = parts.reduce(
    (sum, part) => sum + Number(part.estimatedCost || 0),
    0
  );
  const actualParts = parts.reduce(
    (sum, part) => sum + Number(part.actualCost || 0),
    0
  );
  const expectedBudget = project.expectedBudget ?? project.budgetTarget ?? 0;
  const completedTasks = tasks.filter(
    task => task.status === 'Done' || task.status === 'Completed'
  ).length;

  const lines = [
    `# ${project.name}`,
    '',
    `Generated by Fabricator on ${formatDate(generatedAt.toISOString())}.`,
    '',
    ...section('Project Summary', [
      bullet(`Category: ${project.category || 'General'}`),
      bullet(`Phase: ${project.phase || 'Planning'}`),
      bullet(`Status: ${project.status}`),
      bullet(`Progress: ${project.progress || 0}%`),
      bullet(`Tasks complete: ${completedTasks} of ${tasks.length}`),
      bullet(`Expected budget: ${formatCurrency(expectedBudget)}`),
      bullet(`Estimated parts cost: ${formatCurrency(estimatedParts)}`),
      bullet(`Actual parts cost: ${formatCurrency(actualParts)}`),
      bullet(`Remaining budget: ${formatCurrency(expectedBudget - actualParts)}`),
      bullet(`Last updated: ${formatDate(project.updatedAt)}`),
    ]),
    ...section(
      'Tasks',
      tasks.length
        ? tasks.map(task =>
            bullet(
              `${task.title} | ${task.status} | ${task.system || 'General'} | updated ${formatDate(task.updatedAt)}`
                + (task.priority === 'High' ? ' | next-session priority' : '')
            )
          )
        : ['No tasks recorded.']
    ),
    ...section(
      'Parts',
      parts.length
        ? parts.map(part =>
            bullet(
              [
                part.name,
                normalizePartStatus(part.status),
                part.system || 'General',
                part.vendor ? `vendor: ${part.vendor}` : undefined,
                part.partNumber ? `part #: ${part.partNumber}` : undefined,
                `estimated: ${formatCurrency(part.estimatedCost)}`,
                `actual: ${formatCurrency(part.actualCost)}`,
              ]
                .filter(Boolean)
                .join(' | ')
            )
          )
        : ['No parts recorded.']
    ),
    ...section(
      'Photos',
      photos.length
        ? photos.map(photo =>
            bullet(
              [
                photo.caption || 'Build photo',
                photo.tag || 'Untagged',
                photo.isMilestone ? `milestone: ${photo.milestoneTitle || 'Yes'}` : undefined,
                photo.id === project.coverPhotoId ? 'project cover' : undefined,
                `added ${formatDate(photo.createdAt)}`,
                `uri: ${photo.uri}`,
              ]
                .filter(Boolean)
                .join(' | ')
            )
          )
        : ['No photos recorded.']
    ),
    ...section(
      'Voice Notes',
      voiceNotes.length
        ? voiceNotes.map(note =>
            bullet(`${formatDate(note.createdAt)} | ${note.transcript}`)
          )
        : ['No voice notes recorded.']
    ),
    ...section(
      'Timeline',
      activities.length
        ? activities.map(activity =>
            bullet(
              [
                formatDate(activity.createdAt),
                activity.kind,
                activity.title,
                activity.detail,
              ]
                .filter(Boolean)
                .join(' | ')
            )
          )
        : ['No timeline activity recorded.']
    ),
    'Data note: this export was generated from data available locally in Fabricator on this device.',
    '',
  ];

  return lines.join('\n');
}

export async function exportProjectRecord(input: ProjectExportInput): Promise<ProjectExportResult> {
  if (!FileSystem.documentDirectory) {
    throw new Error('Local document storage is unavailable.');
  }

  const timestamp = new Date()
    .toISOString()
    .replace(/[:.]/g, '-');
  const fileName = `${sanitizeFileName(input.project.name)}-${timestamp}.md`;
  const uri = `${FileSystem.documentDirectory}${fileName}`;
  const markdown = buildProjectExportMarkdown(input);

  await FileSystem.writeAsStringAsync(uri, markdown, {
    encoding: FileSystem.EncodingType.UTF8,
  });

  return {
    fileName,
    uri,
  };
}
